config/routes.rb
RailsChallenge::Application.routes.draw do
  resources :charges

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  attr_accessible :amount, :created, :currency, :customer_id, :paid, :refunded
  belongs_to :customer
  
  scope :failed_charges, -> { where(paid: false, refunded: false) }
  scope :disputed_charges, -> { where(paid: false, refunded: true) }
  scope :successful_charges, -> { where(paid: true, refunded: false) }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :firstname, :lastname
  has_many :charges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
    @failed_charges = Charge.failed_charges
    @disputed_charges = Charge.disputed_charges
    @successful_charges = Charge.successful_charges
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charges }
    end
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @charge = Charge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/new
  # GET /charges/new.json
  def new
    @charge = Charge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/1/edit
  def edit
    @charge = Charge.find(params[:id])
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(params[:charge])

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render json: @charge, status: :created, location: @charge }
      else
        format.html { render action: "new" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charges/1
  # PUT /charges/1.json
  def update
    @charge = Charge.find(params[:id])

    respond_to do |format|
      if @charge.update_attributes(params[:charge])
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy

    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created %><br />
    <%= f.number_field :created %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br />
    <%= f.check_box :refunded %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<script type="text/javascript">
  $(function() {
  // Charge is the app name
  window.router = new RailsChallenge.Routers.ChargesRouter({charges: <%= @charges.to_json.html_safe -%>});
  Backbone.history.start();
  });
</script>

<h1>List1-Failed Charges</h1>
<table>
  <thead>
    <tr>
      <th>Customer firstname</th>
      <th>Customer lastname</th>
      <th>Amount</th>
      <th>Created</th>            
    </tr>
  </thead>

  <tbody>  	
    <% @failed_charges.each do |charge| %>
      <tr class="list1-background">  
      	<td><%= Customer.find(charge.customer_id).firstname %></td>
      	<td><%= Customer.find(charge.customer_id).lastname  %></td>  
      	<td><%= charge.amount %></td>  
        <td><%= charge.created %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>List 2-Disputed Charges</h1>

<table>
  <thead>
    <tr>
      <th>Customer firstname</th>
      <th>Customer lastname</th>
      <th>Amount</th>
      <th>Created</th>            
    </tr>
  </thead>

  <tbody>
    <% @disputed_charges.each do |charge| %>
      <tr class="list2-background">  
      	<td><%= charge.customer.firstname %></td>
      	<td><%= charge.customer.lastname %></td>  
      	<td><%= charge.amount %></td>  
        <td><%= charge.created %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>List3-Successful Charges</h1>

<table>
  <thead>
    <tr>
      <th>Customer firstname</th>
      <th>Customer lastname</th>
      <th>Amount</th>
      <th>Created</th>            
    </tr>
  </thead>

  <tbody>
    <% @successful_charges.each do |charge| %>
        <tr class="list3-background">  
      	<td><%= Customer.find(charge.customer_id).firstname %></td>
      	<td><%= Customer.find(charge.customer_id).lastname  %></td>  
      	<td><%= charge.amount %></td>  
        <td><%= charge.created %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Created:</b>
  <%= @charge.created %>
</p>

<p>
  <b>Paid:</b>
  <%= @charge.paid %>
</p>

<p>
  <b>Amount:</b>
  <%= @charge.amount %>
</p>

<p>
  <b>Currency:</b>
  <%= @charge.currency %>
</p>

<p>
  <b>Refunded:</b>
  <%= @charge.refunded %>
</p>

<p>
  <b>Customer:</b>
  <%= @charge.customer_id %>
</p>


<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>